FROM ubuntu:trusty

RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        git \
        libdbus-1-dev \
        libglib2.0-dev \
        libgtk-3-dev \
        libnotify-dev \
        libpango1.0-dev \
        libx11-dev \
        libxdg-basedir-dev \
        libxinerama-dev \
        libxrandr-dev \
        libxss-dev \
        valgrind \
 && apt-get clean \
 && true

ADD entrypoint-dev.sh /srv/entrypoint

ENTRYPOINT ["/srv/entrypoint"]
