FROM alpine

ENV DUNST_DOCS_ONLY=true \
    SYSTEMD=0 \
    SERVICEDIR_DBUS=/tmp/none \
    SERVICEDIR_SYSTEMD=/tmp/none \
    PKG_CONFIG=echo

RUN apk add --no-cache \
        doxygen \
        git \
        graphviz \
        make \
 && true

ADD entrypoint.sh /srv/entrypoint

ENTRYPOINT ["/srv/entrypoint"]
