FROM fedora:27

RUN true \
 && dnf install -y \
        clang \
        dbus-devel \
        @development-tools \
        glib2-devel \
        libnotify-devel \
        librsvg2 \
        libX11-devel \
        libXrandr-devel \
        libXScrnSaver-devel \
        pango-devel \
        valgrind \
 && true

ADD entrypoint-dev.sh /srv/entrypoint

ENTRYPOINT ["/srv/entrypoint"]
